import * as fs from 'node:fs/promises';
import * as path from 'node:path';
import type { InstanceRecord, InstanceSecrets } from '@mj-forge/shared';

/**
 * Generates the configuration files an MJ worktree needs to run against its
 * isolated SQL Server container:
 *   - `<worktree>/.env`                         — DB connection + API port
 *   - `<worktree>/packages/MJAPI/.env`          — symlink to the root .env
 *   - `<worktree>/packages/MJExplorer/src/environments/environment.ts`
 *   - `<worktree>/packages/MJExplorer/src/environments/environment.development.ts`
 *   - `<worktree>/packages/MJAPI/.mjrc.cjs`       — magic-link config overlay
 *
 * Most settings flow through the generated `.env`, but the magic-link provider's
 * `enabled`/`explorerUrl` are not env-drivable, so they must live in the config
 * that MJServer loads. Rather than clobber the repo's **tracked** `mj.config.cjs`
 * (a footprint + dev-config-leak risk), we write a `.mjrc.cjs` overlay that
 * `require`s the untouched tracked config and overrides only the magic-link block.
 *
 * **Placement matters.** MJServer runs with its cwd at `packages/MJAPI`, and
 * cosmiconfig's `searchStrategy: 'global'` returns the FIRST config found scanning
 * upward — which is `packages/MJAPI/mj.config.cjs` (a tracked one-liner that
 * re-exports the root `mj.config.cjs`). A `.mjrc.cjs` at the worktree *root* is
 * never reached. So the overlay must live at `packages/MJAPI/.mjrc.cjs`, where
 * `.mjrc.cjs` outranks `mj.config.cjs` in the very directory cosmiconfig searches
 * first; its `require('./mj.config.cjs')` resolves to the re-export → the untouched
 * root config. `.mjrc.cjs` is already in MJ's `.gitignore` (matches in any dir), so
 * the tool never modifies a tracked file and needs no new ignore rule.
 */
export class ConfigWriter {
  /**
   * Gitignored config overlay path, RELATIVE TO THE WORKTREE. It lives in
   * `packages/MJAPI` (MJServer's cwd) — not the worktree root — because
   * cosmiconfig stops at `packages/MJAPI/mj.config.cjs` when searching upward and
   * never sees a root-level overlay. Within that dir, `.mjrc.cjs` outranks
   * `mj.config.cjs` in cosmiconfig's default search order, so it wins.
   */
  static readonly MJ_OVERLAY_FILE = 'packages/MJAPI/.mjrc.cjs';

  /**
   * Build the root `.env` body for an instance. Mirrors the variable set MJ's
   * own installer writes (`MJInstaller` ConfigurePhase.writeEnvFile) and the
   * canonical Mac setup guide, so an instance behaves like a hand-set-up
   * checkout — with two deliberate differences: least-privilege logins instead
   * of `sa` (see dbBootstrap.ts), and empty auth (AuthProvider: none, deferred).
   * Exposed for golden-file testing.
   */
  static renderEnv(record: InstanceRecord, secrets: InstanceSecrets): string {
    const { ports, dbName } = record;
    // Pass the dev's AI keys through to the instance when present on the host,
    // so CodeGen/AI features work without per-instance reconfiguration.
    const aiKey = (name: string) => `${name}=${process.env[name] ?? ''}`;
    return [
      `# Generated by MJ Dev Manager — instance "${record.slug}". Do not edit by hand;`,
      `# regenerate from ~/.mjdev/instances/${record.slug}.yaml.`,
      '',
      '# Database',
      'DB_HOST=localhost',
      `DB_PORT=${ports.sql}`,
      `DB_DATABASE=${dbName}`,
      'DB_TRUST_SERVER_CERTIFICATE=1',
      '',
      '# Least-privilege app logins — never `sa` for app access (see dbBootstrap.ts).',
      `CODEGEN_DB_USERNAME=${secrets.codegenUsername}`,
      `CODEGEN_DB_PASSWORD=${secrets.codegenPassword}`,
      `DB_USERNAME=${secrets.dbUsername}`,
      `DB_PASSWORD=${secrets.dbPassword}`,
      `DB_READ_ONLY_USERNAME=${secrets.dbUsername}`,
      `DB_READ_ONLY_PASSWORD=${secrets.dbPassword}`,
      '',
      `# OUTPUT_CODE names generated SQL-script output directories.`,
      `OUTPUT_CODE=${dbName}`,
      'MJ_CORE_SCHEMA=__mj',
      '',
      '# Field-level encryption key (base64 256-bit), auto-generated per instance.',
      `MJ_BASE_ENCRYPTION_KEY=${secrets.encryptionKey}`,
      '',
      '# API server',
      `GRAPHQL_PORT=${ports.api}`,
      'GRAPHQL_BASE_URL=http://localhost',
      'MJAPI_PUBLIC_URL=',
      '',
      '# Auto-create the user cache entry on first run (matches MJ installer defaults).',
      'UPDATE_USER_CACHE_WHEN_NOT_FOUND=1',
      'UPDATE_USER_CACHE_WHEN_NOT_FOUND_DELAY=5000',
      '',
      '# AI provider keys — passed through from the host environment when set.',
      aiKey('AI_VENDOR_API_KEY__OpenAILLM'),
      aiKey('AI_VENDOR_API_KEY__AnthropicLLM'),
      aiKey('AI_VENDOR_API_KEY__MistralLLM'),
      '',
      '# Local dev auth — self-contained magic-link provider (no external IdP).',
      '# MJ_API_KEY: system Owner key. The dev tool sends it as `x-mj-api-key` to',
      '# mint magic-link sessions; MJAPI also accepts it for privileged calls.',
      `MJ_API_KEY=${secrets.systemApiKey ?? ''}`,
      '# RSA private key (base64 PEM) MJAPI signs magic-link session JWTs with;',
      '# generated per instance so sessions survive MJAPI restarts.',
      `MJ_MAGIC_LINK_PRIVATE_KEY=${secrets.magicLinkPrivateKey ?? ''}`,
      '',
      '# Entra/Auth0 left empty — real shared-IdP wiring is deferred (see plan).',
      'WEB_CLIENT_ID=',
      'TENANT_ID=',
      'AUTH0_CLIENT_ID=',
      'AUTH0_CLIENT_SECRET=',
      'AUTH0_DOMAIN=',
      '',
      '# Skip API (MJ defaults)',
      'ASK_SKIP_API_URL=http://localhost:8000',
      'ASK_SKIP_ORGANIZATION_ID=1',
      '',
    ].join('\n');
  }

  /**
   * Build an Explorer environment file body. `production` selects the
   * `environment.ts` (true) vs `environment.development.ts` (false) variant —
   * both are needed: Angular's code imports `./environments/environment`, and
   * the `development` build configuration replaces it with the dev variant.
   */
  static renderExplorerEnv(record: InstanceRecord, production = false): string {
    const { ports } = record;
    const env = {
      GRAPHQL_URI: `http://localhost:${ports.api}/`,
      GRAPHQL_WS_URI: `ws://localhost:${ports.api}/`,
      REDIRECT_URI: `http://localhost:${ports.explorer}/`,
      CLIENT_ID: '',
      TENANT_ID: '',
      CLIENT_AUTHORITY: '',
      // Self-contained local login: MJAPI mints/validates magic-link session
      // JWTs itself, so the Explorer needs no external IdP config.
      AUTH_TYPE: 'magic-link',
      NODE_ENV: production ? 'production' : 'development',
      AUTOSAVE_DEBOUNCE_MS: 1200,
      SEARCH_DEBOUNCE_MS: 800,
      MIN_SEARCH_LENGTH: 3,
      MJ_CORE_SCHEMA_NAME: '__mj',
      production,
      APPLICATION_NAME: `MJ Explorer (${record.name})`,
      APPLICATION_INSTANCE: record.slug,
      AUTH0_DOMAIN: '',
      AUTH0_CLIENTID: '',
    };
    return (
      `// Generated by MJ Dev Manager — instance "${record.slug}".\n` +
      `export const environment = ${JSON.stringify(env, null, 2)};\n`
    );
  }

  /**
   * Build the per-instance `.mjrc.cjs` overlay (written to `packages/MJAPI/`).
   * Its `require('./mj.config.cjs')` resolves to `packages/MJAPI/mj.config.cjs`,
   * the tracked one-liner that re-exports the **untouched** root `mj.config.cjs`,
   * so the overlay spreads the real config and overrides only the `magicLink`
   * block — `enabled` and `explorerUrl` are not env-drivable, so they must live in
   * the config literal MJServer loads. Setting `explorerUrl` per instance also
   * fixes the tracked file's hardcoded `http://localhost:4201`. The signing key
   * (`rsaPrivateKey`) and system `apiKey` still come from `.env`. cosmiconfig
   * (cwd `packages/MJAPI`) loads this `.mjrc.cjs` ahead of `mj.config.cjs`, so the
   * overlay wins without the tool ever modifying a tracked file.
   */
  static renderConfigOverlay(record: InstanceRecord): string {
    const { ports } = record;
    return [
      `// Generated by MJ Dev Manager — instance "${record.slug}". Do not edit by hand.`,
      '// Overlay loaded by cosmiconfig ahead of the tracked mj.config.cjs (which it',
      '// spreads, untouched) — overrides only the magic-link block (not env-drivable).',
      "const base = require('./mj.config.cjs');",
      '',
      'module.exports = {',
      '  ...base,',
      '  magicLink: {',
      '    ...(base.magicLink || {}),',
      '    enabled: true,',
      `    explorerUrl: 'http://localhost:${ports.explorer}',`,
      "    audience: 'mj-magic-link',",
      "    grantableRoleNames: ['Developer', 'UI', 'Integration'],",
      "    // Dev personas are pre-created by the tool, so don't block re-provisioning.",
      "    provisioningGuard: 'warn',",
      '  },',
      '};',
      '',
    ].join('\n');
  }

  /** Write all config files into the worktree and return the paths written. */
  async write(
    worktreePath: string,
    record: InstanceRecord,
    secrets: InstanceSecrets
  ): Promise<string[]> {
    const written: string[] = [];

    const rootEnv = path.join(worktreePath, '.env');
    await fs.writeFile(rootEnv, ConfigWriter.renderEnv(record, secrets));
    written.push(rootEnv);

    // MJAPI reads its own .env; symlink it to the root file so they stay in sync.
    const apiDir = path.join(worktreePath, 'packages', 'MJAPI');
    if (await ConfigWriter.dirExists(apiDir)) {
      const apiEnv = path.join(apiDir, '.env');
      await fs.rm(apiEnv, { force: true });
      await fs.symlink(path.relative(apiDir, rootEnv), apiEnv).catch(async () => {
        // Fall back to a copy if symlinks aren't permitted (e.g. some Windows setups).
        await fs.copyFile(rootEnv, apiEnv);
      });
      written.push(apiEnv);
    }

    // The Explorer's environment files are gitignored, so a fresh worktree has
    // neither the files nor the directory. Create it and write BOTH variants:
    // `environment.ts` (imported directly by app code; used by production
    // builds) and `environment.development.ts` (swapped in by the `development`
    // build configuration that `ng serve` uses). Skipping either makes the
    // Angular build fail with a missing-file-replacement error.
    const explorerSrc = path.join(worktreePath, 'packages', 'MJExplorer', 'src');
    if (await ConfigWriter.dirExists(explorerSrc)) {
      const envDir = path.join(explorerSrc, 'environments');
      await fs.mkdir(envDir, { recursive: true });

      const baseEnv = path.join(envDir, 'environment.ts');
      await fs.writeFile(baseEnv, ConfigWriter.renderExplorerEnv(record, true));
      written.push(baseEnv);

      const devEnv = path.join(envDir, 'environment.development.ts');
      await fs.writeFile(devEnv, ConfigWriter.renderExplorerEnv(record, false));
      written.push(devEnv);
    }

    // Enable magic-link via a gitignored `.mjrc.cjs` overlay in packages/MJAPI —
    // MJServer's cwd, and where cosmiconfig (searchStrategy 'global') stops first
    // at the tracked `packages/MJAPI/mj.config.cjs` re-export. A root-level overlay
    // would never be reached. The overlay requires that re-export (→ the untouched
    // root config) and overrides only the magic-link block: the tracked file is
    // never modified (no footprint, no dev-config leak) and no new ignore rule is
    // needed. Only write it when packages/MJAPI/mj.config.cjs exists (real MJ checkout).
    const apiConfig = path.join(worktreePath, 'packages', 'MJAPI', 'mj.config.cjs');
    if (await ConfigWriter.pathExists(apiConfig)) {
      const overlay = path.join(worktreePath, ConfigWriter.MJ_OVERLAY_FILE);
      await fs.writeFile(overlay, ConfigWriter.renderConfigOverlay(record));
      written.push(overlay);
    }

    return written;
  }

  private static async dirExists(dir: string): Promise<boolean> {
    try {
      return (await fs.stat(dir)).isDirectory();
    } catch {
      return false;
    }
  }

  private static async pathExists(p: string): Promise<boolean> {
    try {
      await fs.stat(p);
      return true;
    } catch {
      return false;
    }
  }
}
