import * as fs from 'node:fs/promises';
import * as path from 'node:path';
import type { InstanceRecord, InstanceSecrets } from '@mj-forge/shared';

/**
 * Generates the configuration files an MJ worktree needs to run against its
 * isolated SQL Server container:
 *   - `<worktree>/.env`                         — DB connection + API port
 *   - `<worktree>/packages/MJAPI/.env`          — symlink to the root .env
 *   - `<worktree>/packages/MJExplorer/src/environments/environment.development.ts`
 *
 * `mj.config.cjs` is tracked in the repo and reads everything from these env
 * vars, so it needs no per-instance generation.
 */
export class ConfigWriter {
  /** Build the `.env` body for an instance. Exposed for golden-file testing. */
  static renderEnv(record: InstanceRecord, secrets: InstanceSecrets): string {
    const { ports, dbName } = record;
    return [
      `# Generated by MJ Dev Manager — instance "${record.slug}". Do not edit by hand;`,
      `# regenerate from ~/.mjdev/instances/${record.slug}.yaml.`,
      '',
      'DB_HOST=localhost',
      `DB_PORT=${ports.sql}`,
      `DB_DATABASE=${dbName}`,
      `DB_USERNAME=${secrets.dbUsername}`,
      `DB_PASSWORD=${secrets.dbPassword}`,
      'DB_TRUST_SERVER_CERTIFICATE=true',
      `CODEGEN_DB_USERNAME=${secrets.codegenUsername}`,
      `CODEGEN_DB_PASSWORD=${secrets.codegenPassword}`,
      'MJ_CORE_SCHEMA=__mj',
      '',
      `GRAPHQL_PORT=${ports.api}`,
      'GRAPHQL_BASE_URL=http://localhost',
      '',
      '# Auth is deferred in MVP (AuthProvider: none). MJAPI runs without it;',
      '# MJExplorer login requires WEB_CLIENT_ID / TENANT_ID to be filled in.',
      'WEB_CLIENT_ID=',
      'TENANT_ID=',
      '',
    ].join('\n');
  }

  /** Build the Explorer `environment.development.ts` body. */
  static renderExplorerEnv(record: InstanceRecord): string {
    const { ports } = record;
    const env = {
      GRAPHQL_URI: `http://localhost:${ports.api}/`,
      GRAPHQL_WS_URI: `ws://localhost:${ports.api}/`,
      REDIRECT_URI: `http://localhost:${ports.explorer}/`,
      CLIENT_ID: '',
      TENANT_ID: '',
      CLIENT_AUTHORITY: '',
      AUTH_TYPE: '',
      NODE_ENV: 'development',
      AUTOSAVE_DEBOUNCE_MS: 1200,
      SEARCH_DEBOUNCE_MS: 800,
      MIN_SEARCH_LENGTH: 3,
      MJ_CORE_SCHEMA_NAME: '__mj',
      production: false,
      APPLICATION_NAME: `MJ Explorer (${record.name})`,
      APPLICATION_INSTANCE: record.slug,
      AUTH0_DOMAIN: '',
      AUTH0_CLIENTID: '',
    };
    return (
      `// Generated by MJ Dev Manager — instance "${record.slug}".\n` +
      `export const environment = ${JSON.stringify(env, null, 2)};\n`
    );
  }

  /** Write all config files into the worktree and return the paths written. */
  async write(
    worktreePath: string,
    record: InstanceRecord,
    secrets: InstanceSecrets
  ): Promise<string[]> {
    const written: string[] = [];

    const rootEnv = path.join(worktreePath, '.env');
    await fs.writeFile(rootEnv, ConfigWriter.renderEnv(record, secrets));
    written.push(rootEnv);

    // MJAPI reads its own .env; symlink it to the root file so they stay in sync.
    const apiDir = path.join(worktreePath, 'packages', 'MJAPI');
    if (await ConfigWriter.dirExists(apiDir)) {
      const apiEnv = path.join(apiDir, '.env');
      await fs.rm(apiEnv, { force: true });
      await fs.symlink(path.relative(apiDir, rootEnv), apiEnv).catch(async () => {
        // Fall back to a copy if symlinks aren't permitted (e.g. some Windows setups).
        await fs.copyFile(rootEnv, apiEnv);
      });
      written.push(apiEnv);
    }

    const envDir = path.join(worktreePath, 'packages', 'MJExplorer', 'src', 'environments');
    if (await ConfigWriter.dirExists(envDir)) {
      const explorerEnv = path.join(envDir, 'environment.development.ts');
      await fs.writeFile(explorerEnv, ConfigWriter.renderExplorerEnv(record));
      written.push(explorerEnv);
    }

    return written;
  }

  private static async dirExists(dir: string): Promise<boolean> {
    try {
      return (await fs.stat(dir)).isDirectory();
    } catch {
      return false;
    }
  }
}
