import * as fs from 'node:fs/promises';
import * as path from 'node:path';
import type { InstanceRecord, InstanceSecrets } from '@mj-forge/shared';

/**
 * Generates the configuration files an MJ worktree needs to run against its
 * isolated SQL Server container:
 *   - `<worktree>/.env`                         — DB connection + API port
 *   - `<worktree>/packages/MJAPI/.env`          — symlink to the root .env
 *   - `<worktree>/packages/MJExplorer/src/environments/environment.ts`
 *   - `<worktree>/packages/MJExplorer/src/environments/environment.development.ts`
 *
 * `mj.config.cjs` is tracked in the repo and reads everything from these env
 * vars, so it needs no per-instance generation.
 */
export class ConfigWriter {
  /**
   * Build the root `.env` body for an instance. Mirrors the variable set MJ's
   * own installer writes (`MJInstaller` ConfigurePhase.writeEnvFile) and the
   * canonical Mac setup guide, so an instance behaves like a hand-set-up
   * checkout — with two deliberate differences: least-privilege logins instead
   * of `sa` (see dbBootstrap.ts), and empty auth (AuthProvider: none, deferred).
   * Exposed for golden-file testing.
   */
  static renderEnv(record: InstanceRecord, secrets: InstanceSecrets): string {
    const { ports, dbName } = record;
    // Pass the dev's AI keys through to the instance when present on the host,
    // so CodeGen/AI features work without per-instance reconfiguration.
    const aiKey = (name: string) => `${name}=${process.env[name] ?? ''}`;
    return [
      `# Generated by MJ Dev Manager — instance "${record.slug}". Do not edit by hand;`,
      `# regenerate from ~/.mjdev/instances/${record.slug}.yaml.`,
      '',
      '# Database',
      'DB_HOST=localhost',
      `DB_PORT=${ports.sql}`,
      `DB_DATABASE=${dbName}`,
      'DB_TRUST_SERVER_CERTIFICATE=1',
      '',
      '# Least-privilege app logins — never `sa` for app access (see dbBootstrap.ts).',
      `CODEGEN_DB_USERNAME=${secrets.codegenUsername}`,
      `CODEGEN_DB_PASSWORD=${secrets.codegenPassword}`,
      `DB_USERNAME=${secrets.dbUsername}`,
      `DB_PASSWORD=${secrets.dbPassword}`,
      `DB_READ_ONLY_USERNAME=${secrets.dbUsername}`,
      `DB_READ_ONLY_PASSWORD=${secrets.dbPassword}`,
      '',
      `# OUTPUT_CODE names generated SQL-script output directories.`,
      `OUTPUT_CODE=${dbName}`,
      'MJ_CORE_SCHEMA=__mj',
      '',
      '# Field-level encryption key (base64 256-bit), auto-generated per instance.',
      `MJ_BASE_ENCRYPTION_KEY=${secrets.encryptionKey}`,
      '',
      '# API server',
      `GRAPHQL_PORT=${ports.api}`,
      'GRAPHQL_BASE_URL=http://localhost',
      'MJAPI_PUBLIC_URL=',
      '',
      '# Auto-create the user cache entry on first run (matches MJ installer defaults).',
      'UPDATE_USER_CACHE_WHEN_NOT_FOUND=1',
      'UPDATE_USER_CACHE_WHEN_NOT_FOUND_DELAY=5000',
      '',
      '# AI provider keys — passed through from the host environment when set.',
      aiKey('AI_VENDOR_API_KEY__OpenAILLM'),
      aiKey('AI_VENDOR_API_KEY__AnthropicLLM'),
      aiKey('AI_VENDOR_API_KEY__MistralLLM'),
      '',
      '# Auth is deferred in MVP (AuthProvider: none). MJAPI runs without it;',
      '# MJExplorer login requires the Entra (WEB_CLIENT_ID/TENANT_ID) or AUTH0_* block.',
      'WEB_CLIENT_ID=',
      'TENANT_ID=',
      'AUTH0_CLIENT_ID=',
      'AUTH0_CLIENT_SECRET=',
      'AUTH0_DOMAIN=',
      '',
      '# Skip API (MJ defaults)',
      'ASK_SKIP_API_URL=http://localhost:8000',
      'ASK_SKIP_ORGANIZATION_ID=1',
      '',
    ].join('\n');
  }

  /**
   * Build an Explorer environment file body. `production` selects the
   * `environment.ts` (true) vs `environment.development.ts` (false) variant —
   * both are needed: Angular's code imports `./environments/environment`, and
   * the `development` build configuration replaces it with the dev variant.
   */
  static renderExplorerEnv(record: InstanceRecord, production = false): string {
    const { ports } = record;
    const env = {
      GRAPHQL_URI: `http://localhost:${ports.api}/`,
      GRAPHQL_WS_URI: `ws://localhost:${ports.api}/`,
      REDIRECT_URI: `http://localhost:${ports.explorer}/`,
      CLIENT_ID: '',
      TENANT_ID: '',
      CLIENT_AUTHORITY: '',
      AUTH_TYPE: '',
      NODE_ENV: production ? 'production' : 'development',
      AUTOSAVE_DEBOUNCE_MS: 1200,
      SEARCH_DEBOUNCE_MS: 800,
      MIN_SEARCH_LENGTH: 3,
      MJ_CORE_SCHEMA_NAME: '__mj',
      production,
      APPLICATION_NAME: `MJ Explorer (${record.name})`,
      APPLICATION_INSTANCE: record.slug,
      AUTH0_DOMAIN: '',
      AUTH0_CLIENTID: '',
    };
    return (
      `// Generated by MJ Dev Manager — instance "${record.slug}".\n` +
      `export const environment = ${JSON.stringify(env, null, 2)};\n`
    );
  }

  /** Write all config files into the worktree and return the paths written. */
  async write(
    worktreePath: string,
    record: InstanceRecord,
    secrets: InstanceSecrets
  ): Promise<string[]> {
    const written: string[] = [];

    const rootEnv = path.join(worktreePath, '.env');
    await fs.writeFile(rootEnv, ConfigWriter.renderEnv(record, secrets));
    written.push(rootEnv);

    // MJAPI reads its own .env; symlink it to the root file so they stay in sync.
    const apiDir = path.join(worktreePath, 'packages', 'MJAPI');
    if (await ConfigWriter.dirExists(apiDir)) {
      const apiEnv = path.join(apiDir, '.env');
      await fs.rm(apiEnv, { force: true });
      await fs.symlink(path.relative(apiDir, rootEnv), apiEnv).catch(async () => {
        // Fall back to a copy if symlinks aren't permitted (e.g. some Windows setups).
        await fs.copyFile(rootEnv, apiEnv);
      });
      written.push(apiEnv);
    }

    // The Explorer's environment files are gitignored, so a fresh worktree has
    // neither the files nor the directory. Create it and write BOTH variants:
    // `environment.ts` (imported directly by app code; used by production
    // builds) and `environment.development.ts` (swapped in by the `development`
    // build configuration that `ng serve` uses). Skipping either makes the
    // Angular build fail with a missing-file-replacement error.
    const explorerSrc = path.join(worktreePath, 'packages', 'MJExplorer', 'src');
    if (await ConfigWriter.dirExists(explorerSrc)) {
      const envDir = path.join(explorerSrc, 'environments');
      await fs.mkdir(envDir, { recursive: true });

      const baseEnv = path.join(envDir, 'environment.ts');
      await fs.writeFile(baseEnv, ConfigWriter.renderExplorerEnv(record, true));
      written.push(baseEnv);

      const devEnv = path.join(envDir, 'environment.development.ts');
      await fs.writeFile(devEnv, ConfigWriter.renderExplorerEnv(record, false));
      written.push(devEnv);
    }

    return written;
  }

  private static async dirExists(dir: string): Promise<boolean> {
    try {
      return (await fs.stat(dir)).isDirectory();
    } catch {
      return false;
    }
  }
}
