/**
 * Source for the **worktree-resident** open-app engine entrypoint.
 *
 * This string is written into the instance's MJ worktree (under an
 * `info/exclude`-hidden `.mjdev/` scratch dir) and executed with the instance's
 * Node, so its bare-specifier `import`s resolve to the worktree's OWN built
 * `@memberjunction/sqlserver-dataprovider` + `@memberjunction/open-app-engine`
 * (+ `mssql`, all hoisted to the worktree root `node_modules`). That guarantees a
 * dev-link runs the EXACT engine code a real `mj app install` would run in that
 * worktree — the production-structure-parity keystone. A Forge-pinned engine copy
 * would risk version skew; this never does.
 *
 * Protocol: structured events are emitted to stdout as single-line JSON prefixed
 * with {@link ENGINE_EVENT_SENTINEL}. Everything else on stdout (the provider's
 * verbose boot logging) is forwarded as plain info. The job spec is read from the
 * file path passed as argv[2].
 *
 * The source is kept dependency-free of any Forge code and uses only dynamic
 * `import()` of the worktree packages, so it is valid regardless of whether those
 * packages ship as ESM or CJS. It deliberately avoids template literals so it can
 * live inside a `String.raw` literal without escaping.
 */
export const ENGINE_EVENT_SENTINEL = '@@MJDEV-ENGINE@@';

export const ENGINE_ENTRY_SOURCE = String.raw`// GENERATED by @mj-forge/orchestrator — runs INSIDE an MJ instance worktree.
// Invokes the worktree's own @memberjunction/open-app-engine for true parity.
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { createRequire } from 'node:module';

const SENTINEL = '@@MJDEV-ENGINE@@';
const require = createRequire(import.meta.url);

function send(kind, phase, message, data) {
  process.stdout.write(
    SENTINEL + JSON.stringify({ kind: kind, phase: phase, message: message || '', data: data || null }) + '\n'
  );
}

function readMjVersion() {
  try {
    return require('@memberjunction/core/package.json').version;
  } catch (e) {
    return 'unknown';
  }
}

// Reproduce the engine's NON-exported RemoveAppEntityMetadata (install-orchestrator.ts):
// delete the app schema's MJ entity registrations in FK-dependency order. Required so
// a reset's re-Migrate (or a full remove) doesn't collide with __mj rows a migration
// seeded (e.g. SchemaInfo with a hardcoded UUID). Mirrors the engine's RunView+Delete
// approach verbatim (incl. .Get('ID'), matching the source) for parity.
async function cleanAppMetadata(ctx, schemaName) {
  const core = await import('@memberjunction/core');
  const esc = ctx.engine.EscapeSqlString(schemaName);
  const rv = new core.RunView();
  const del = async function (entityName, filter) {
    const r = await rv.RunView({ EntityName: entityName, ExtraFilter: filter, ResultType: 'entity_object' }, ctx.contextUser);
    if (r.Success) for (const rec of r.Results) await rec.Delete();
  };
  const er = await rv.RunView(
    { EntityName: 'MJ: Entities', ExtraFilter: "SchemaName = '" + esc + "'", ResultType: 'entity_object' },
    ctx.contextUser
  );
  if (!er.Success) return;
  if (er.Results.length === 0) {
    await del('MJ: Schema Info', "SchemaName = '" + esc + "'");
    return;
  }
  const idList = er.Results.map(function (e) { return "'" + ctx.engine.EscapeSqlString(String(e.Get('ID'))) + "'"; }).join(',');
  const filt = 'EntityID IN (' + idList + ')';
  await del('MJ: Entity Permissions', filt);
  await del('MJ: Application Entities', filt);
  await del('MJ: Entity Relationships', 'EntityID IN (' + idList + ') OR RelatedEntityID IN (' + idList + ')');
  await del('MJ: Entity Fields', filt);
  for (const e of er.Results) await e.Delete();
  await del('MJ: Schema Info', "SchemaName = '" + esc + "'");
}

// Build a Skyway instance directly (RunAppMigrations exposes only Migrate/Close,
// so Clean/Repair/Validate for recovery + drift detection need direct construction).
async function buildSkyway(ctx) {
  const skMod = await import('@memberjunction/skyway-core');
  const provMod = await import('@memberjunction/skyway-sqlserver');
  const db = ctx.dbConfig;
  const isAzure = db.Host.indexOf('.database.windows.net') >= 0;
  const cfg = {
    Database: {
      Server: db.Host,
      Port: db.Port,
      Database: db.Database,
      User: db.User,
      Password: db.Password,
      Options: { Encrypt: isAzure, TrustServerCertificate: !isAzure },
    },
    Migrations: {
      Locations: [resolve(ctx.spec.memberPath, ctx.manifest.migrations.directory)],
      DefaultSchema: ctx.manifest.schema.name,
      BaselineVersion: '1',
      BaselineOnMigrate: true,
    },
    Placeholders: { 'flyway:defaultSchema': ctx.manifest.schema.name, mjSchema: ctx.mjCoreSchema },
  };
  cfg.Provider = new provMod.SqlServerProvider(cfg.Database);
  return new skMod.Skyway(cfg);
}

// Build the engine OrchestratorContext from the booted ctx + job spec. Shared by the
// install and removeApp steps (both call the engine's GitHub-coupled orchestrators).
function buildOrchestratorContext(ctx) {
  return {
    ContextUser: ctx.contextUser,
    DatabaseProvider: ctx.provider,
    DatabaseConfig: ctx.dbConfig,
    GitHubOptions: { Token: ctx.spec.githubToken || process.env.GITHUB_TOKEN },
    RepoRoot: ctx.spec.repoRoot,
    MJVersion: ctx.mjVersion,
    ServerPackagePath: ctx.spec.serverPackagePath,
    ClientPackagePath: ctx.spec.clientPackagePath,
    ClientBootstrapSubpath: ctx.spec.clientBootstrapSubpath,
    MJCoreSchema: ctx.mjCoreSchema,
    Callbacks: {
      OnProgress: function (phase, message) { send('progress', phase || 'Engine', message || ''); },
      OnError: function (phase, message) { send('error', phase || 'Engine', message || ''); },
    },
  };
}

async function runStep(step, ctx) {
  const engine = ctx.engine;

  if (step === 'checkVersion') {
    // Parity: a real install fails on an incompatible MJ version. Dev-link honors
    // that by default, but allows an explicit ignoreVersionRange override (warned).
    const r = engine.CheckMJVersionCompatibility(ctx.mjVersion, ctx.manifest.mjVersionRange);
    if (!r.Compatible) {
      if (ctx.spec.ignoreVersionRange) {
        send('progress', 'Version', 'OVERRIDE: ' + (r.Message || 'incompatible') + ' (ignoreVersionRange)');
        return { compatible: false, overridden: true, range: ctx.manifest.mjVersionRange, mjVersion: ctx.mjVersion };
      }
      throw new Error('MJ version ' + ctx.mjVersion + ' not in range ' + ctx.manifest.mjVersionRange + ': ' + (r.Message || ''));
    }
    send('success', 'Version', 'MJ ' + ctx.mjVersion + ' satisfies ' + ctx.manifest.mjVersionRange);
    return { compatible: true, range: ctx.manifest.mjVersionRange, mjVersion: ctx.mjVersion };
  }

  if (step === 'install') {
    // Plain install via the engine's exported InstallApp — the real 'mj app install'
    // path with NO dev seams, so it is maximal parity by construction. Fetches the app
    // AND its full transitive open-app dependency graph from GitHub (leaf-first), runs
    // each app's migrations, mutates mj.config.cjs / angular.json / package deps,
    // installs npm packages, and records every MJ: Open Apps row Active. (The dev-link
    // path instead reproduces the granular shell against LOCAL source.)
    if (!ctx.spec.source) throw new Error('install requires spec.source (GitHub URL)');
    const orCtx = buildOrchestratorContext(ctx);
    send('progress', 'Install', 'Installing ' + ctx.spec.source + (ctx.spec.version ? ' @ ' + ctx.spec.version : '') + ' (+ transitive deps)');
    const ir = await engine.InstallApp(
      {
        Source: ctx.spec.source,
        Version: ctx.spec.version,
        Verbose: true,
        AllowDoubleUnderscoreSchema: ctx.spec.allowDoubleUnderscore === true,
      },
      orCtx
    );
    if (!ir.Success) {
      throw new Error('InstallApp failed (' + (ir.ErrorPhase || '?') + '): ' + (ir.ErrorMessage || 'unknown'));
    }
    // InstallApp can return Success while leaving the app DISABLED (e.g. its npm install
    // failed) — the reason + finish steps live in ir.Summary. Surface that Summary and
    // downgrade the level to 'warn' when disabled, so a watcher isn't misled by a clean
    // "Installed" line into thinking the app is Active.
    const leftDisabled = /disabled/i.test(ir.Summary || '');
    const installMsg = 'Installed ' + ir.AppName + ' v' + ir.Version + ' (' + ir.DurationSeconds + 's)';
    send(leftDisabled ? 'warn' : 'success', 'Install', installMsg + (ir.Summary ? ' — ' + ir.Summary : ''));
    return { appName: ir.AppName, version: ir.Version, action: ir.Action, durationSeconds: ir.DurationSeconds, summary: ir.Summary || null, disabled: leftDisabled };
  }

  if (step === 'removeApp') {
    // Uninstall an INSTALLED app via the engine's exported RemoveApp (inverse of
    // InstallApp): reverse package/config mutations, set the MJ: Open Apps row Removed,
    // and DROP the schema unless keepData. Identified by manifest name. (Dev-linked apps
    // are torn down by the reproduced unlink shell instead.)
    if (!ctx.spec.appName) throw new Error('removeApp requires spec.appName (manifest name)');
    const orCtx = buildOrchestratorContext(ctx);
    send('progress', 'Remove', 'Removing ' + ctx.spec.appName + (ctx.spec.keepData ? ' (keep data)' : ' (drop schema)'));
    const rr = await engine.RemoveApp(
      {
        AppName: ctx.spec.appName,
        KeepData: ctx.spec.keepData === true,
        Force: ctx.spec.force === true,
        Verbose: true,
        AllowDoubleUnderscoreSchema: ctx.spec.allowDoubleUnderscore === true,
      },
      orCtx
    );
    if (!rr.Success) {
      throw new Error('RemoveApp failed (' + (rr.ErrorPhase || '?') + '): ' + (rr.ErrorMessage || 'unknown'));
    }
    send('success', 'Remove', 'Removed ' + rr.AppName + ' (' + (rr.Summary || 'done') + ')');
    return { appName: rr.AppName, action: rr.Action, summary: rr.Summary || null };
  }

  if (step === 'driftCheck') {
    // Active checksum-drift detection: Skyway.Validate() verifies applied-migration
    // checksums against disk (Migrate() silently skips edited versioned files).
    if (!ctx.manifest || !ctx.manifest.schema || !ctx.manifest.migrations) {
      return { skipped: true, reason: 'no migrations' };
    }
    const sk = await buildSkyway(ctx);
    try {
      const v = await sk.Validate();
      if (v.Valid) send('success', 'Drift', 'No checksum drift');
      else send('error', 'Drift', 'DRIFT: ' + v.Errors.join('; '));
      return { valid: v.Valid, errors: v.Errors };
    } finally {
      await sk.Close().catch(function () {});
    }
  }

  if (step === 'resetSchema') {
    // Destructive recovery for an edited versioned migration: Clean() then Migrate().
    if (!ctx.manifest || !ctx.manifest.schema || !ctx.manifest.migrations) {
      return { skipped: true, reason: 'no migrations' };
    }
    const sk = await buildSkyway(ctx);
    try {
      send('progress', 'Reset', 'Cleaning schema ' + ctx.manifest.schema.name + ' (destructive)');
      const c = await sk.Clean();
      if (!c.Success) throw new Error('Clean failed: ' + c.ErrorMessage);
      // Also remove the app's __mj entity metadata so re-Migrate's seed inserts
      // (e.g. SchemaInfo) don't collide — mirrors the engine's remove flow.
      await cleanAppMetadata(ctx, ctx.manifest.schema.name);
      const m = await sk.Migrate();
      if (!m.Success) throw new Error('Re-migrate failed: ' + m.ErrorMessage);
      send('success', 'Reset', 'Dropped ' + c.ObjectsDropped + ' object(s), re-applied ' + m.MigrationsApplied);
      return { objectsDropped: c.ObjectsDropped, reapplied: m.MigrationsApplied };
    } finally {
      await sk.Close().catch(function () {});
    }
  }

  if (step === 'repairSchema') {
    // Repair() realigns failed/baseline history rows; it does NOT re-run SQL.
    if (!ctx.manifest || !ctx.manifest.schema || !ctx.manifest.migrations) {
      return { skipped: true, reason: 'no migrations' };
    }
    const sk = await buildSkyway(ctx);
    try {
      const r = await sk.Repair();
      if (!r.Success) throw new Error('Repair failed: ' + r.ErrorMessage);
      send('success', 'Repair', 'Removed ' + r.FailedEntriesRemoved + ' failed, realigned ' + r.ChecksumsRealigned);
      return { failedEntriesRemoved: r.FailedEntriesRemoved, checksumsRealigned: r.ChecksumsRealigned, details: r.RepairDetails };
    } finally {
      await sk.Close().catch(function () {});
    }
  }

  if (step === 'ensureSchema') {
    if (!ctx.manifest || !ctx.manifest.schema) return { skipped: true, reason: 'no schema in manifest' };
    const name = ctx.manifest.schema.name;
    send('progress', 'Schema', 'Checking schema ' + name);
    const exists = await engine.SchemaExists(name, ctx.provider);
    if (exists) {
      send('success', 'Schema', 'Schema ' + name + ' already exists');
      return { schema: name, created: false };
    }
    const r = await engine.CreateAppSchema(name, ctx.provider, {
      allowDoubleUnderscore: ctx.spec.allowDoubleUnderscore === true,
    });
    if (!r.Success) throw new Error('create schema failed: ' + r.ErrorMessage);
    send('success', 'Schema', 'Created schema ' + name);
    return { schema: name, created: true };
  }

  if (step === 'migrate') {
    if (!ctx.manifest || !ctx.manifest.schema || !ctx.manifest.migrations) {
      return { skipped: true, reason: 'no migrations in manifest' };
    }
    const dir = resolve(ctx.spec.memberPath, ctx.manifest.migrations.directory);
    send('progress', 'Migrate', 'Running migrations from ' + dir);
    const r = await engine.RunAppMigrations({
      MigrationsDir: dir,
      SchemaName: ctx.manifest.schema.name,
      DatabaseConfig: ctx.dbConfig,
      MJCoreSchema: ctx.mjCoreSchema,
    });
    if (!r.Success) throw new Error('migrations failed: ' + r.ErrorMessage);
    send('success', 'Migrate', 'Applied ' + r.MigrationsApplied + ' migration(s)');
    return { applied: r.MigrationsApplied, files: r.AppliedFiles, schema: ctx.manifest.schema.name };
  }

  if (step === 'record') {
    // Reproduce the install orchestrator's RecordInstallationAtomically: create
    // the MJ: Open Apps row (status 'Installing') inside a TransactionGroup, plus
    // dependency rows. Idempotent: reuse an existing non-Removed row.
    const core = await import('@memberjunction/core');
    const existing = await engine.FindInstalledApp(ctx.contextUser, ctx.manifest.name);
    if (existing && existing.Status !== 'Removed') {
      ctx.appId = existing.ID;
      send('success', 'Record', 'Reusing app record ' + existing.ID + ' (' + existing.Status + ')');
      return { appId: existing.ID, reused: true, status: existing.Status };
    }
    const md = new core.Metadata();
    const tg = await md.CreateTransactionGroup();
    const appId = await engine.RecordAppInstallation(ctx.contextUser, ctx.manifest, undefined, tg, 'Installing');
    if (ctx.manifest.dependencies && Object.keys(ctx.manifest.dependencies).length > 0) {
      await engine.RecordAppDependencies(ctx.contextUser, appId, ctx.manifest.dependencies, tg);
    }
    const ok = await tg.Submit();
    if (!ok) throw new Error('failed to commit installation record (transaction)');
    ctx.appId = appId;
    send('success', 'Record', 'Recorded app installation ' + appId);
    return { appId: appId, reused: false };
  }

  if (step === 'addPackages') {
    if (!ctx.manifest.packages) return { skipped: true, reason: 'no packages in manifest' };
    send('progress', 'Packages', 'Adding app package deps + installing');
    const add = engine.AddAppPackages({
      RepoRoot: ctx.spec.repoRoot,
      ServerPackages: ctx.manifest.packages.server || [],
      ClientPackages: ctx.manifest.packages.client || [],
      SharedPackages: ctx.manifest.packages.shared || [],
      Version: ctx.manifest.version,
      ServerPackagePath: ctx.spec.serverPackagePath,
      ClientPackagePath: ctx.spec.clientPackagePath,
      PackageManager: 'npm',
    });
    if (!add.Success) throw new Error('AddAppPackages failed: ' + add.ErrorMessage);
    const inst = engine.RunPackageInstall(ctx.spec.repoRoot, false, ctx.manifest.packages.registry, 'npm');
    if (!inst.Success) throw new Error('RunPackageInstall failed: ' + inst.ErrorMessage);
    send('success', 'Packages', 'Packages added + installed');
    return { added: true };
  }

  if (step === 'serverConfig') {
    // Server dynamicPackages via the exported handler. The entityPackageName
    // mapping (NOT exported) is reproduced Forge-side on mj.config.cjs.
    const r = engine.AddServerDynamicPackages(ctx.spec.repoRoot, ctx.manifest);
    if (!r.Success) throw new Error('AddServerDynamicPackages failed: ' + r.ErrorMessage);
    send('success', 'Config', 'Updated dynamicPackages.server');
    return { ok: true };
  }

  if (step === 'angularExcludes') {
    const mgr = new engine.AngularConfigManager(ctx.spec.repoRoot, ctx.spec.clientPackagePath);
    if (!mgr.Load()) {
      send('progress', 'Angular', 'angular.json not found; skipping prebundle excludes');
      return { skipped: true, reason: 'no angular.json' };
    }
    const n = mgr.AddPrebundleExcludes(ctx.manifest);
    const save = mgr.Save();
    if (!save.Success) throw new Error('angular.json save failed: ' + save.ErrorMessage);
    send('success', 'Angular', 'Added ' + n + ' prebundle exclude(s)');
    return { added: n };
  }

  if (step === 'setActive') {
    if (!ctx.appId) throw new Error('setActive requires a prior record step');
    await engine.SetAppStatus(ctx.contextUser, ctx.appId, 'Active');
    send('success', 'Record', 'App status -> Active');
    return { appId: ctx.appId, status: 'Active' };
  }

  if (step === 'clientBootstrap') {
    // Current MJ registers a dev-linked app's client classes via config: the engine's
    // AddClientDynamicPackages(repoRoot, manifest) writes dynamicPackages.client, and
    // MJExplorer's "mj codegen manifest --ln" prebuild turns each into a per-app
    // side-effect import (firing its @RegisterClass decorators). Mirrors serverConfig.
    // It's additive, so only run it for the app being LINKED (Status Active); on unlink
    // it's a no-op, because removeServerConfig (RemoveServerDynamicPackages) already
    // sweeps the client array.
    if (typeof engine.AddClientDynamicPackages !== 'function') {
      // The worktree's engine doesn't expose the client-bootstrap API this step needs,
      // so dynamicPackages.client could not be written and the app's UI won't load.
      // Surface it loudly with both plausible causes rather than guessing one.
      throw new Error(
        'Client-bootstrap step failed: the MJ engine in this instance worktree does not ' +
          'expose AddClientDynamicPackages, so dynamicPackages.client was not written. ' +
          'This may be because the instance worktree was built from an OLDER MJ source ' +
          '(rebuild the instance engine and retry), OR because MJ has changed the open-app ' +
          'client-bootstrap API again (the dev-manager tool needs updating to match). ' +
          'Check the current open-app config API on this MJ base.'
      );
    }
    const installed = await engine.ListInstalledApps(ctx.contextUser);
    const me = installed.find(a => a.Name === ctx.manifest.name);
    if (me && me.Status === 'Active') {
      const r = engine.AddClientDynamicPackages(ctx.spec.repoRoot, ctx.manifest);
      if (!r.Success) throw new Error('AddClientDynamicPackages failed: ' + r.ErrorMessage);
      send('success', 'Config', 'Updated dynamicPackages.client (built by mj codegen manifest --ln)');
      return { mode: 'dynamicPackages.client', added: true };
    }
    send('info', 'Config', 'Client packages swept with config (no add for removed/inactive app)');
    return { mode: 'dynamicPackages.client', added: false };
  }

  if (step === 'removeServerConfig') {
    const r = engine.RemoveServerDynamicPackages(ctx.spec.repoRoot, ctx.manifest.name);
    if (!r.Success) throw new Error('RemoveServerDynamicPackages failed: ' + r.ErrorMessage);
    send('success', 'Config', 'Removed dynamicPackages.server for ' + ctx.manifest.name);
    return { ok: true };
  }

  if (step === 'removePackages') {
    // Remove declared deps from package.json only; the final npm install is run
    // Forge-side AFTER the member worktree is removed (avoids an extra install).
    if (!ctx.manifest.packages) return { skipped: true, reason: 'no packages' };
    const r = engine.RemoveAppPackages({
      RepoRoot: ctx.spec.repoRoot,
      ServerPackages: ctx.manifest.packages.server || [],
      ClientPackages: ctx.manifest.packages.client || [],
      SharedPackages: ctx.manifest.packages.shared || [],
      Version: ctx.manifest.version,
      ServerPackagePath: ctx.spec.serverPackagePath,
      ClientPackagePath: ctx.spec.clientPackagePath,
      PackageManager: 'npm',
    });
    if (!r.Success) throw new Error('RemoveAppPackages failed: ' + r.ErrorMessage);
    send('success', 'Packages', 'Removed app package deps');
    return { removed: true };
  }

  if (step === 'removeAngularExcludes') {
    const mgr = new engine.AngularConfigManager(ctx.spec.repoRoot, ctx.spec.clientPackagePath);
    if (!mgr.Load()) return { skipped: true, reason: 'no angular.json' };
    const n = mgr.RemovePrebundleExcludes(ctx.manifest, ctx.spec.otherManifests || []);
    const save = mgr.Save();
    if (!save.Success) throw new Error('angular.json save failed: ' + save.ErrorMessage);
    send('success', 'Angular', 'Removed ' + n + ' prebundle exclude(s)');
    return { removed: n };
  }

  if (step === 'setRemoved') {
    const app = await engine.FindInstalledApp(ctx.contextUser, ctx.manifest.name);
    if (!app) return { skipped: true, reason: 'app not recorded' };
    await engine.SetAppStatus(ctx.contextUser, app.ID, 'Removed');
    send('success', 'Record', 'App status -> Removed');
    return { appId: app.ID, status: 'Removed' };
  }

  if (step === 'cleanMetadata') {
    const name = ctx.manifest && ctx.manifest.schema ? ctx.manifest.schema.name : ctx.spec.schemaName;
    if (!name) return { skipped: true, reason: 'no schema' };
    await cleanAppMetadata(ctx, name);
    send('success', 'Metadata', 'Removed MJ entity metadata for schema ' + name);
    return { schema: name, cleaned: true };
  }

  if (step === 'dropSchema') {
    const name = ctx.manifest && ctx.manifest.schema ? ctx.manifest.schema.name : ctx.spec.schemaName;
    if (!name) return { skipped: true, reason: 'no schema' };
    const r = await engine.DropAppSchema(name, ctx.provider, {
      allowDoubleUnderscore: ctx.spec.allowDoubleUnderscore === true,
    });
    if (!r.Success) throw new Error('DropAppSchema failed: ' + r.ErrorMessage);
    send('success', 'Schema', 'Dropped schema ' + name);
    return { schema: name, dropped: true };
  }

  if (step === 'listApps') {
    const apps = await engine.ListInstalledApps(ctx.contextUser);
    return {
      apps: apps.map(a => ({ Name: a.Name, Version: a.Version, Status: a.Status, SchemaName: a.SchemaName })),
    };
  }

  if (step === 'schemaInfo') {
    // Read the per-app flyway_schema_history so callers can prove migrations
    // tracked in the APP schema (not __mj) and detect checksum drift later.
    const name = ctx.manifest && ctx.manifest.schema ? ctx.manifest.schema.name : ctx.spec.schemaName;
    if (!name) return { skipped: true, reason: 'no schema name' };
    const rows = await ctx.provider.ExecuteSQL(
      "SELECT [version] AS Version, [description] AS Description, [checksum] AS Checksum, " +
      "[success] AS Success, [type] AS Type FROM [" + name.replace(/]/g, ']]') +
      "].flyway_schema_history ORDER BY installed_rank"
    );
    return { schema: name, history: rows };
  }

  throw new Error('unknown step: ' + step);
}

async function main() {
  const specPath = process.argv[2];
  if (!specPath) throw new Error('missing job spec path (argv[2])');
  const spec = JSON.parse(readFileSync(specPath, 'utf-8'));
  const db = spec.dbConfig;
  const mjCoreSchema = spec.mjCoreSchema || '__mj';

  send('progress', 'Boot', 'Booting MJ data provider');
  const sql = (await import('mssql')).default;
  const sdp = await import('@memberjunction/sqlserver-dataprovider');
  const engine = await import('@memberjunction/open-app-engine');

  const pool = new sql.ConnectionPool({
    server: db.host,
    port: db.port,
    database: db.database,
    user: db.user,
    password: db.password,
    options: {
      encrypt: db.encrypt === true,
      trustServerCertificate: db.trustServerCertificate !== false,
      enableArithAbort: true,
    },
  });
  await pool.connect();

  try {
    const provider = await sdp.setupSQLServerClient(new sdp.SQLServerProviderConfigData(pool, mjCoreSchema));
    const uc = sdp.UserCache.Instance;
    const contextUser =
      uc.GetSystemUser() ||
      uc.Users.find(function (u) { return u.IsActive && u.Type === 'Owner'; }) ||
      uc.Users.find(function (u) { return u.IsActive; });
    if (!contextUser) throw new Error('No users in UserCache; cannot determine system user');
    send('progress', 'Boot', 'Provider ready as ' + contextUser.Email);

    const dbConfig = {
      Host: db.host,
      Port: db.port,
      Database: db.database,
      User: db.user,
      Password: db.password,
      Encrypt: db.encrypt === true,
      TrustServerCertificate: db.trustServerCertificate !== false,
    };

    let manifest = null;
    if (spec.manifestPath) {
      const mr = engine.LoadManifestFromFile(spec.manifestPath);
      if (!mr.Success || !mr.Manifest) {
        throw new Error('manifest load failed: ' + ((mr.Errors || []).join('; ')));
      }
      manifest = mr.Manifest;
    }

    const ctx = {
      engine: engine,
      provider: provider,
      contextUser: contextUser,
      dbConfig: dbConfig,
      manifest: manifest,
      spec: spec,
      mjCoreSchema: mjCoreSchema,
      mjVersion: readMjVersion(),
      appId: null,
    };

    const results = {};
    for (const step of spec.steps) {
      results[step] = await runStep(step, ctx);
    }
    send('result', 'Done', 'All steps complete', { results: results, mjVersion: readMjVersion() });
  } finally {
    try { await pool.close(); } catch (e) { /* ignore */ }
  }
}

main().then(
  function () { process.exit(0); },
  function (err) {
    send('error', 'Fatal', err && err.message ? err.message : String(err));
    process.exit(1);
  }
);
`;
