/**
 * Source for the **worktree-resident** open-app engine entrypoint.
 *
 * This string is written into the instance's MJ worktree (under an
 * `info/exclude`-hidden `.mjdev/` scratch dir) and executed with the instance's
 * Node, so its bare-specifier `import`s resolve to the worktree's OWN built
 * `@memberjunction/sqlserver-dataprovider` + `@memberjunction/open-app-engine`
 * (+ `mssql`, all hoisted to the worktree root `node_modules`). That guarantees a
 * dev-link runs the EXACT engine code a real `mj app install` would run in that
 * worktree — the production-structure-parity keystone. A Forge-pinned engine copy
 * would risk version skew; this never does.
 *
 * Protocol: structured events are emitted to stdout as single-line JSON prefixed
 * with {@link ENGINE_EVENT_SENTINEL}. Everything else on stdout (the provider's
 * verbose boot logging) is forwarded as plain info. The job spec is read from the
 * file path passed as argv[2].
 *
 * The source is kept dependency-free of any Forge code and uses only dynamic
 * `import()` of the worktree packages, so it is valid regardless of whether those
 * packages ship as ESM or CJS. It deliberately avoids template literals so it can
 * live inside a `String.raw` literal without escaping.
 */
export const ENGINE_EVENT_SENTINEL = '@@MJDEV-ENGINE@@';

export const ENGINE_ENTRY_SOURCE = String.raw`// GENERATED by @mj-forge/orchestrator — runs INSIDE an MJ instance worktree.
// Invokes the worktree's own @memberjunction/open-app-engine for true parity.
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { createRequire } from 'node:module';

const SENTINEL = '@@MJDEV-ENGINE@@';
const require = createRequire(import.meta.url);

function send(kind, phase, message, data) {
  process.stdout.write(
    SENTINEL + JSON.stringify({ kind: kind, phase: phase, message: message || '', data: data || null }) + '\n'
  );
}

function readMjVersion() {
  try {
    return require('@memberjunction/core/package.json').version;
  } catch (e) {
    return 'unknown';
  }
}

async function runStep(step, ctx) {
  const engine = ctx.engine;
  if (step === 'ensureSchema') {
    if (!ctx.manifest || !ctx.manifest.schema) return { skipped: true, reason: 'no schema in manifest' };
    const name = ctx.manifest.schema.name;
    send('progress', 'Schema', 'Checking schema ' + name);
    const exists = await engine.SchemaExists(name, ctx.provider);
    if (exists) {
      send('success', 'Schema', 'Schema ' + name + ' already exists');
      return { schema: name, created: false };
    }
    const r = await engine.CreateAppSchema(name, ctx.provider, {
      allowDoubleUnderscore: ctx.spec.allowDoubleUnderscore === true,
    });
    if (!r.Success) throw new Error('create schema failed: ' + r.ErrorMessage);
    send('success', 'Schema', 'Created schema ' + name);
    return { schema: name, created: true };
  }

  if (step === 'migrate') {
    if (!ctx.manifest || !ctx.manifest.schema || !ctx.manifest.migrations) {
      return { skipped: true, reason: 'no migrations in manifest' };
    }
    const dir = resolve(ctx.spec.memberPath, ctx.manifest.migrations.directory);
    send('progress', 'Migrate', 'Running migrations from ' + dir);
    const r = await engine.RunAppMigrations({
      MigrationsDir: dir,
      SchemaName: ctx.manifest.schema.name,
      DatabaseConfig: ctx.dbConfig,
      MJCoreSchema: ctx.mjCoreSchema,
    });
    if (!r.Success) throw new Error('migrations failed: ' + r.ErrorMessage);
    send('success', 'Migrate', 'Applied ' + r.MigrationsApplied + ' migration(s)');
    return { applied: r.MigrationsApplied, files: r.AppliedFiles, schema: ctx.manifest.schema.name };
  }

  if (step === 'schemaInfo') {
    // Read the per-app flyway_schema_history so callers can prove migrations
    // tracked in the APP schema (not __mj) and detect checksum drift later.
    const name = ctx.manifest && ctx.manifest.schema ? ctx.manifest.schema.name : ctx.spec.schemaName;
    if (!name) return { skipped: true, reason: 'no schema name' };
    const rows = await ctx.provider.ExecuteSQL(
      "SELECT [version] AS Version, [description] AS Description, [checksum] AS Checksum, " +
      "[success] AS Success, [type] AS Type FROM [" + name.replace(/]/g, ']]') +
      "].flyway_schema_history ORDER BY installed_rank"
    );
    return { schema: name, history: rows };
  }

  throw new Error('unknown step: ' + step);
}

async function main() {
  const specPath = process.argv[2];
  if (!specPath) throw new Error('missing job spec path (argv[2])');
  const spec = JSON.parse(readFileSync(specPath, 'utf-8'));
  const db = spec.dbConfig;
  const mjCoreSchema = spec.mjCoreSchema || '__mj';

  send('progress', 'Boot', 'Booting MJ data provider');
  const sql = (await import('mssql')).default;
  const sdp = await import('@memberjunction/sqlserver-dataprovider');
  const engine = await import('@memberjunction/open-app-engine');

  const pool = new sql.ConnectionPool({
    server: db.host,
    port: db.port,
    database: db.database,
    user: db.user,
    password: db.password,
    options: {
      encrypt: db.encrypt === true,
      trustServerCertificate: db.trustServerCertificate !== false,
      enableArithAbort: true,
    },
  });
  await pool.connect();

  try {
    const provider = await sdp.setupSQLServerClient(new sdp.SQLServerProviderConfigData(pool, mjCoreSchema));
    const uc = sdp.UserCache.Instance;
    const contextUser =
      uc.GetSystemUser() ||
      uc.Users.find(function (u) { return u.IsActive && u.Type === 'Owner'; }) ||
      uc.Users.find(function (u) { return u.IsActive; });
    if (!contextUser) throw new Error('No users in UserCache; cannot determine system user');
    send('progress', 'Boot', 'Provider ready as ' + contextUser.Email);

    const dbConfig = {
      Host: db.host,
      Port: db.port,
      Database: db.database,
      User: db.user,
      Password: db.password,
      Encrypt: db.encrypt === true,
      TrustServerCertificate: db.trustServerCertificate !== false,
    };

    let manifest = null;
    if (spec.manifestPath) {
      const mr = engine.LoadManifestFromFile(spec.manifestPath);
      if (!mr.Success || !mr.Manifest) {
        throw new Error('manifest load failed: ' + ((mr.Errors || []).join('; ')));
      }
      manifest = mr.Manifest;
    }

    const ctx = {
      engine: engine,
      provider: provider,
      contextUser: contextUser,
      dbConfig: dbConfig,
      manifest: manifest,
      spec: spec,
      mjCoreSchema: mjCoreSchema,
    };

    const results = {};
    for (const step of spec.steps) {
      results[step] = await runStep(step, ctx);
    }
    send('result', 'Done', 'All steps complete', { results: results, mjVersion: readMjVersion() });
  } finally {
    try { await pool.close(); } catch (e) { /* ignore */ }
  }
}

main().then(
  function () { process.exit(0); },
  function (err) {
    send('error', 'Fatal', err && err.message ? err.message : String(err));
    process.exit(1);
  }
);
`;
