/**
 * Source for the **worktree-resident** open-app engine entrypoint.
 *
 * This string is written into the instance's MJ worktree (under an
 * `info/exclude`-hidden `.mjdev/` scratch dir) and executed with the instance's
 * Node, so its bare-specifier `import`s resolve to the worktree's OWN built
 * `@memberjunction/sqlserver-dataprovider` + `@memberjunction/open-app-engine`
 * (+ `mssql`, all hoisted to the worktree root `node_modules`). That guarantees a
 * dev-link runs the EXACT engine code a real `mj app install` would run in that
 * worktree — the production-structure-parity keystone. A Forge-pinned engine copy
 * would risk version skew; this never does.
 *
 * Protocol: structured events are emitted to stdout as single-line JSON prefixed
 * with {@link ENGINE_EVENT_SENTINEL}. Everything else on stdout (the provider's
 * verbose boot logging) is forwarded as plain info. The job spec is read from the
 * file path passed as argv[2].
 *
 * The source is kept dependency-free of any Forge code and uses only dynamic
 * `import()` of the worktree packages, so it is valid regardless of whether those
 * packages ship as ESM or CJS. It deliberately avoids template literals so it can
 * live inside a `String.raw` literal without escaping.
 */
export const ENGINE_EVENT_SENTINEL = '@@MJDEV-ENGINE@@';

export const ENGINE_ENTRY_SOURCE = String.raw`// GENERATED by @mj-forge/orchestrator — runs INSIDE an MJ instance worktree.
// Invokes the worktree's own @memberjunction/open-app-engine for true parity.
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { createRequire } from 'node:module';

const SENTINEL = '@@MJDEV-ENGINE@@';
const require = createRequire(import.meta.url);

function send(kind, phase, message, data) {
  process.stdout.write(
    SENTINEL + JSON.stringify({ kind: kind, phase: phase, message: message || '', data: data || null }) + '\n'
  );
}

function readMjVersion() {
  try {
    return require('@memberjunction/core/package.json').version;
  } catch (e) {
    return 'unknown';
  }
}

async function runStep(step, ctx) {
  const engine = ctx.engine;
  if (step === 'ensureSchema') {
    if (!ctx.manifest || !ctx.manifest.schema) return { skipped: true, reason: 'no schema in manifest' };
    const name = ctx.manifest.schema.name;
    send('progress', 'Schema', 'Checking schema ' + name);
    const exists = await engine.SchemaExists(name, ctx.provider);
    if (exists) {
      send('success', 'Schema', 'Schema ' + name + ' already exists');
      return { schema: name, created: false };
    }
    const r = await engine.CreateAppSchema(name, ctx.provider, {
      allowDoubleUnderscore: ctx.spec.allowDoubleUnderscore === true,
    });
    if (!r.Success) throw new Error('create schema failed: ' + r.ErrorMessage);
    send('success', 'Schema', 'Created schema ' + name);
    return { schema: name, created: true };
  }

  if (step === 'migrate') {
    if (!ctx.manifest || !ctx.manifest.schema || !ctx.manifest.migrations) {
      return { skipped: true, reason: 'no migrations in manifest' };
    }
    const dir = resolve(ctx.spec.memberPath, ctx.manifest.migrations.directory);
    send('progress', 'Migrate', 'Running migrations from ' + dir);
    const r = await engine.RunAppMigrations({
      MigrationsDir: dir,
      SchemaName: ctx.manifest.schema.name,
      DatabaseConfig: ctx.dbConfig,
      MJCoreSchema: ctx.mjCoreSchema,
    });
    if (!r.Success) throw new Error('migrations failed: ' + r.ErrorMessage);
    send('success', 'Migrate', 'Applied ' + r.MigrationsApplied + ' migration(s)');
    return { applied: r.MigrationsApplied, files: r.AppliedFiles, schema: ctx.manifest.schema.name };
  }

  if (step === 'record') {
    // Reproduce the install orchestrator's RecordInstallationAtomically: create
    // the MJ: Open Apps row (status 'Installing') inside a TransactionGroup, plus
    // dependency rows. Idempotent: reuse an existing non-Removed row.
    const core = await import('@memberjunction/core');
    const existing = await engine.FindInstalledApp(ctx.contextUser, ctx.manifest.name);
    if (existing && existing.Status !== 'Removed') {
      ctx.appId = existing.ID;
      send('success', 'Record', 'Reusing app record ' + existing.ID + ' (' + existing.Status + ')');
      return { appId: existing.ID, reused: true, status: existing.Status };
    }
    const md = new core.Metadata();
    const tg = await md.CreateTransactionGroup();
    const appId = await engine.RecordAppInstallation(ctx.contextUser, ctx.manifest, undefined, tg, 'Installing');
    if (ctx.manifest.dependencies && Object.keys(ctx.manifest.dependencies).length > 0) {
      await engine.RecordAppDependencies(ctx.contextUser, appId, ctx.manifest.dependencies, tg);
    }
    const ok = await tg.Submit();
    if (!ok) throw new Error('failed to commit installation record (transaction)');
    ctx.appId = appId;
    send('success', 'Record', 'Recorded app installation ' + appId);
    return { appId: appId, reused: false };
  }

  if (step === 'addPackages') {
    if (!ctx.manifest.packages) return { skipped: true, reason: 'no packages in manifest' };
    send('progress', 'Packages', 'Adding app package deps + installing');
    const add = engine.AddAppPackages({
      RepoRoot: ctx.spec.repoRoot,
      ServerPackages: ctx.manifest.packages.server || [],
      ClientPackages: ctx.manifest.packages.client || [],
      SharedPackages: ctx.manifest.packages.shared || [],
      Version: ctx.manifest.version,
      ServerPackagePath: ctx.spec.serverPackagePath,
      ClientPackagePath: ctx.spec.clientPackagePath,
      PackageManager: 'npm',
    });
    if (!add.Success) throw new Error('AddAppPackages failed: ' + add.ErrorMessage);
    const inst = engine.RunPackageInstall(ctx.spec.repoRoot, false, ctx.manifest.packages.registry, 'npm');
    if (!inst.Success) throw new Error('RunPackageInstall failed: ' + inst.ErrorMessage);
    send('success', 'Packages', 'Packages added + installed');
    return { added: true };
  }

  if (step === 'serverConfig') {
    // Server dynamicPackages via the exported handler. The entityPackageName
    // mapping (NOT exported) is reproduced Forge-side on mj.config.cjs.
    const r = engine.AddServerDynamicPackages(ctx.spec.repoRoot, ctx.manifest);
    if (!r.Success) throw new Error('AddServerDynamicPackages failed: ' + r.ErrorMessage);
    send('success', 'Config', 'Updated dynamicPackages.server');
    return { ok: true };
  }

  if (step === 'angularExcludes') {
    const mgr = new engine.AngularConfigManager(ctx.spec.repoRoot, ctx.spec.clientPackagePath);
    if (!mgr.Load()) {
      send('progress', 'Angular', 'angular.json not found; skipping prebundle excludes');
      return { skipped: true, reason: 'no angular.json' };
    }
    const n = mgr.AddPrebundleExcludes(ctx.manifest);
    const save = mgr.Save();
    if (!save.Success) throw new Error('angular.json save failed: ' + save.ErrorMessage);
    send('success', 'Angular', 'Added ' + n + ' prebundle exclude(s)');
    return { added: n };
  }

  if (step === 'setActive') {
    if (!ctx.appId) throw new Error('setActive requires a prior record step');
    await engine.SetAppStatus(ctx.contextUser, ctx.appId, 'Active');
    send('success', 'Record', 'App status -> Active');
    return { appId: ctx.appId, status: 'Active' };
  }

  if (step === 'clientBootstrap') {
    // Reproduce HandleClientBootstrapRegeneration: topo-sort installed apps
    // (deps first), emit client+shared package entries, regenerate the bootstrap.
    const apps = await engine.ListInstalledApps(ctx.contextUser);
    const appDeps = new Map();
    for (const a of apps) {
      const m = JSON.parse(a.ManifestJSON);
      appDeps.set(a.Name, m.dependencies ? Object.keys(m.dependencies) : []);
    }
    const visited = new Set();
    const sorted = [];
    const visit = name => {
      if (visited.has(name)) return;
      visited.add(name);
      for (const d of appDeps.get(name) || []) if (appDeps.has(d)) visit(d);
      sorted.push(name);
    };
    for (const name of appDeps.keys()) visit(name);
    const byName = new Map(apps.map(a => [a.Name, a]));
    const entries = [];
    for (const name of sorted) {
      const a = byName.get(name);
      if (!a) continue;
      const m = JSON.parse(a.ManifestJSON);
      const pkgs = (m.packages && m.packages.client ? m.packages.client : []).concat(
        m.packages && m.packages.shared ? m.packages.shared : []
      );
      for (const pkg of pkgs) {
        entries.push({ AppName: a.Name, Version: a.Version, PackageName: pkg.name, Enabled: a.Status === 'Active' });
      }
    }
    engine.RegenerateClientBootstrap(ctx.spec.repoRoot, entries, ctx.spec.clientPackagePath, ctx.spec.clientBootstrapSubpath);
    send('success', 'Config', 'Regenerated client bootstrap (' + entries.length + ' entr(ies))');
    return { entries: entries.length };
  }

  if (step === 'listApps') {
    const apps = await engine.ListInstalledApps(ctx.contextUser);
    return {
      apps: apps.map(a => ({ Name: a.Name, Version: a.Version, Status: a.Status, SchemaName: a.SchemaName })),
    };
  }

  if (step === 'schemaInfo') {
    // Read the per-app flyway_schema_history so callers can prove migrations
    // tracked in the APP schema (not __mj) and detect checksum drift later.
    const name = ctx.manifest && ctx.manifest.schema ? ctx.manifest.schema.name : ctx.spec.schemaName;
    if (!name) return { skipped: true, reason: 'no schema name' };
    const rows = await ctx.provider.ExecuteSQL(
      "SELECT [version] AS Version, [description] AS Description, [checksum] AS Checksum, " +
      "[success] AS Success, [type] AS Type FROM [" + name.replace(/]/g, ']]') +
      "].flyway_schema_history ORDER BY installed_rank"
    );
    return { schema: name, history: rows };
  }

  throw new Error('unknown step: ' + step);
}

async function main() {
  const specPath = process.argv[2];
  if (!specPath) throw new Error('missing job spec path (argv[2])');
  const spec = JSON.parse(readFileSync(specPath, 'utf-8'));
  const db = spec.dbConfig;
  const mjCoreSchema = spec.mjCoreSchema || '__mj';

  send('progress', 'Boot', 'Booting MJ data provider');
  const sql = (await import('mssql')).default;
  const sdp = await import('@memberjunction/sqlserver-dataprovider');
  const engine = await import('@memberjunction/open-app-engine');

  const pool = new sql.ConnectionPool({
    server: db.host,
    port: db.port,
    database: db.database,
    user: db.user,
    password: db.password,
    options: {
      encrypt: db.encrypt === true,
      trustServerCertificate: db.trustServerCertificate !== false,
      enableArithAbort: true,
    },
  });
  await pool.connect();

  try {
    const provider = await sdp.setupSQLServerClient(new sdp.SQLServerProviderConfigData(pool, mjCoreSchema));
    const uc = sdp.UserCache.Instance;
    const contextUser =
      uc.GetSystemUser() ||
      uc.Users.find(function (u) { return u.IsActive && u.Type === 'Owner'; }) ||
      uc.Users.find(function (u) { return u.IsActive; });
    if (!contextUser) throw new Error('No users in UserCache; cannot determine system user');
    send('progress', 'Boot', 'Provider ready as ' + contextUser.Email);

    const dbConfig = {
      Host: db.host,
      Port: db.port,
      Database: db.database,
      User: db.user,
      Password: db.password,
      Encrypt: db.encrypt === true,
      TrustServerCertificate: db.trustServerCertificate !== false,
    };

    let manifest = null;
    if (spec.manifestPath) {
      const mr = engine.LoadManifestFromFile(spec.manifestPath);
      if (!mr.Success || !mr.Manifest) {
        throw new Error('manifest load failed: ' + ((mr.Errors || []).join('; ')));
      }
      manifest = mr.Manifest;
    }

    const ctx = {
      engine: engine,
      provider: provider,
      contextUser: contextUser,
      dbConfig: dbConfig,
      manifest: manifest,
      spec: spec,
      mjCoreSchema: mjCoreSchema,
      appId: null,
    };

    const results = {};
    for (const step of spec.steps) {
      results[step] = await runStep(step, ctx);
    }
    send('result', 'Done', 'All steps complete', { results: results, mjVersion: readMjVersion() });
  } finally {
    try { await pool.close(); } catch (e) { /* ignore */ }
  }
}

main().then(
  function () { process.exit(0); },
  function (err) {
    send('error', 'Fatal', err && err.message ? err.message : String(err));
    process.exit(1);
  }
);
`;
